# Basic Site Settings
url                      : https://r-orelli.eu
baseurl                  : "" 
repository               : "s-orion10/s-orion10.github.io"

# Site Author
author:
  avatar           : "profile_ph.jpg"
  name             : "Simone Orelli"
  pronouns         : #"he/him"
  bio              : "Since 1997. Computer Science Engineer. Control System Engineer. Ph.D. in Automatic Control, Bioengineering and Operations Research. DIAG Sapienza University of Rome. 'Where is everyone?'"
  location         : "Rome, Italy"
  employer         : "Universit√† 'Sapienza' of Rome"
  uri              : # URL
  email            : "schol@r-orelli.eu"

  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    :
  impactstory      : # URL
  orcid            : "0009-0007-6613-8597"
  semantic         : # URL
  pubmed           :
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "s-orion10"
  kaggle           : # Username
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")

  # Social media
  instagram        : s_orion10 # Username
  linkedin         : simone-orelli-a5b9a1144 # Username
  youtube          : simoneorelli4296 # Username
